import type { SampleProfile } from './types';

export const sampleProfiles: SampleProfile[] = [
  {
    name: 'Maria - Work-Study Student',
    description: 'Full-time sophomore, work-study eligible, low income',
    data: {
      studentName: 'Maria Garcia',
      age: 20,
      isUSCitizenOrEligibleNoncitizen: true,
      adjustedGrossIncome: 8500,
      parentAGI: 35000,
      untaxedIncome: 0,
      totalIncome: 8500,
      studentAidIndex: -1500,
      enrollmentStatus: 'full-time',
      enrollmentLevel: 'undergraduate',
      householdSize: 1,
      dependencyStatus: 'dependent',
      numberOfDependents: 0,
      hasChildUnder6: false,
      hasChild6to12: false,
      workStudyEligible: true,
      workStudyAmount: 3000,
      currentWorkHoursPerWeek: 15,
      receivingTANF: false,
      receivingDisabilityBenefits: false,
      paResident: true,
    },
  },
  {
    name: 'James - Working Student',
    description: 'Part-time student, works 25 hrs/week at campus dining',
    data: {
      studentName: 'James Thompson',
      age: 22,
      isUSCitizenOrEligibleNoncitizen: true,
      adjustedGrossIncome: 14000,
      parentAGI: null,
      untaxedIncome: 500,
      totalIncome: 14500,
      studentAidIndex: 200,
      enrollmentStatus: 'half-time',
      enrollmentLevel: 'undergraduate',
      householdSize: 1,
      dependencyStatus: 'independent',
      numberOfDependents: 0,
      hasChildUnder6: false,
      hasChild6to12: false,
      workStudyEligible: false,
      workStudyAmount: 0,
      currentWorkHoursPerWeek: 25,
      receivingTANF: false,
      receivingDisabilityBenefits: false,
      paResident: true,
    },
  },
  {
    name: 'Aisha - Student Parent',
    description: 'Independent student with a 3-year-old, receiving TANF',
    data: {
      studentName: 'Aisha Williams',
      age: 26,
      isUSCitizenOrEligibleNoncitizen: true,
      adjustedGrossIncome: 12000,
      parentAGI: null,
      untaxedIncome: 2400,
      totalIncome: 14400,
      studentAidIndex: -500,
      enrollmentStatus: 'full-time',
      enrollmentLevel: 'undergraduate',
      householdSize: 2,
      dependencyStatus: 'independent',
      numberOfDependents: 1,
      hasChildUnder6: true,
      hasChild6to12: false,
      workStudyEligible: false,
      workStudyAmount: 0,
      currentWorkHoursPerWeek: 0,
      receivingTANF: true,
      receivingDisabilityBenefits: false,
      paResident: true,
    },
  },
  {
    name: 'Derek - Over Income',
    description: 'Full-time MBA student with a well-paying internship',
    data: {
      studentName: 'Derek Chen',
      age: 28,
      isUSCitizenOrEligibleNoncitizen: true,
      adjustedGrossIncome: 52000,
      parentAGI: null,
      untaxedIncome: 0,
      totalIncome: 52000,
      studentAidIndex: 8500,
      enrollmentStatus: 'full-time',
      enrollmentLevel: 'graduate',
      householdSize: 1,
      dependencyStatus: 'independent',
      numberOfDependents: 0,
      hasChildUnder6: false,
      hasChild6to12: false,
      workStudyEligible: false,
      workStudyAmount: 0,
      currentWorkHoursPerWeek: 30,
      receivingTANF: false,
      receivingDisabilityBenefits: false,
      paResident: true,
    },
  },
  {
    name: 'Taylor - No Exemption',
    description: 'Full-time student, no work, no work-study, no dependents',
    data: {
      studentName: 'Taylor Brooks',
      age: 19,
      isUSCitizenOrEligibleNoncitizen: true,
      adjustedGrossIncome: 3000,
      parentAGI: 45000,
      untaxedIncome: 0,
      totalIncome: 3000,
      studentAidIndex: 1000,
      enrollmentStatus: 'full-time',
      enrollmentLevel: 'undergraduate',
      householdSize: 1,
      dependencyStatus: 'dependent',
      numberOfDependents: 0,
      hasChildUnder6: false,
      hasChild6to12: false,
      workStudyEligible: false,
      workStudyAmount: 0,
      currentWorkHoursPerWeek: 0,
      receivingTANF: false,
      receivingDisabilityBenefits: false,
      paResident: true,
    },
  },
];
